name: flutter_restaurant
description: "flutter_restaurant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - images/burger.jpg
    - images/cheesechilly.jpg
    - images/noodles.jpg
    - images/pizza.jpg
    - images/hawkers.jpg
    - images/bluehill.jpg
    - images/pizzahut.jpg
    - images/flipping.jpg
    - assets/data.json

  fonts:
    - family: Samantha
      fonts:
        - asset: fonts/Samantha.ttf